# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postimagegalery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagegalery',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery', to='core.Post'),
        ),
    ]
